version: 0.2

env:
  variables:
    AWS_REGION: "ap-southeast-2"

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo Installing npm dependencies for Node.js app
      - npm install && cd ..
  
  pre_build:
    commands:
      - echo Logging in to Amazon ECR
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin 003380495206.dkr.ecr.ap-southeast-2.amazonaws.com
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)

  build:
    commands:
      # Node.js app
      - echo Building Node.js app Docker image
      - docker build -t 003380495206.dkr.ecr.ap-southeast-2.amazonaws.com/nodejs-app:$IMAGE_TAG ./nodejs-app
      - docker tag 003380495206.dkr.ecr.ap-southeast-2.amazonaws.com/nodejs-app:$IMAGE_TAG 003380495206.dkr.ecr.ap-southeast-2.amazonaws.com/nodejs-app:latest

      # MQTT broker
      - echo Building MQTT broker Docker image
      - docker build -t 003380495206.dkr.ecr.ap-southeast-2.amazonaws.com/mqtt-broker:$IMAGE_TAG ./mqtt-broker
      - docker tag 003380495206.dkr.ecr.ap-southeast-2.amazonaws.com/mqtt-broker:$IMAGE_TAG 003380495206.dkr.ecr.ap-southeast-2.amazonaws.com/mqtt-broker:latest

      # Node-RED / Weight Sensor
      - echo Building Weight Sensor Docker image
      - docker build -t 003380495206.dkr.ecr.ap-southeast-2.amazonaws.com/weight-sensor:$IMAGE_TAG ./weight-sensor
      - docker tag 003380495206.dkr.ecr.ap-southeast-2.amazonaws.com/weight-sensor:$IMAGE_TAG 003380495206.dkr.ecr.ap-southeast-2.amazonaws.com/weight-sensor:latest

  post_build:
    commands:
      - echo Pushing Docker images to ECR

      # Node.js app
      - docker push 003380495206.dkr.ecr.ap-southeast-2.amazonaws.com/nodejs-app:$IMAGE_TAG
      - docker push 003380495206.dkr.ecr.ap-southeast-2.amazonaws.com/nodejs-app:latest

      # MQTT broker
      - docker push 003380495206.dkr.ecr.ap-southeast-2.amazonaws.com/mqtt-broker:$IMAGE_TAG
      - docker push 003380495206.dkr.ecr.ap-southeast-2.amazonaws.com/mqtt-broker:latest

      # Weight Sensor
      - docker push 003380495206.dkr.ecr.ap-southeast-2.amazonaws.com/weight-sensor:$IMAGE_TAG
      - docker push 003380495206.dkr.ecr.ap-southeast-2.amazonaws.com/weight-sensor:latest

      - echo Writing image definitions file for ECS
      - printf '[{"name":"nodejs-app","imageUri":"%s"},{"name":"mqtt-broker","imageUri":"%s"},{"name":"weight-sensor","imageUri":"%s"}]' \
        003380495206.dkr.ecr.ap-southeast-2.amazonaws.com/nodejs-app:$IMAGE_TAG \
        003380495206.dkr.ecr.ap-southeast-2.amazonaws.com/mqtt-broker:$IMAGE_TAG \
        003380495206.dkr.ecr.ap-southeast-2.amazonaws.com/weight-sensor:$IMAGE_TAG \
        > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
