version: 0.2

env:
  variables:
    NODEJS_APP_ECR: "003380495206.dkr.ecr.ap-southeast-2.amazonaws.com/nodejs-app"
    AWS_REGION: "ap-southeast-2"

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo Installing dependencies
      - npm install

  pre_build:
    commands:
      - echo Logging in to Amazon ECR
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $NODEJS_APP_ECR
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)

  build:
    commands:
      - echo Building Node.js app Docker image
      - docker build -t nodejs-app:$IMAGE_TAG .
      - docker tag nodejs-app:$IMAGE_TAG $NODEJS_APP_ECR:$IMAGE_TAG
      - docker tag nodejs-app:$IMAGE_TAG $NODEJS_APP_ECR:latest

  post_build:
    commands:
      - echo Pushing Docker image to ECR
      - docker push $NODEJS_APP_ECR:$IMAGE_TAG
      - docker push $NODEJS_APP_ECR:latest
      - echo Writing image definitions file
      - printf '[{"name":"nodejs-app","imageUri":"%s"}]' $NODEJS_APP_ECR:$IMAGE_TAG > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
